[package]
name = "extractousex_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustler = "0.37.0"
extractous = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
